env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io

builds:
- env:
    - CGO_ENABLED=0
  binary: stix2rdf
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  hooks:
    post: /bin/sh script.sh

archives:
  -
    name_template: 'Stix2RDF_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip

sign:
   artifacts: all
   signature: "${artifact}.sig"
